# Config file for the ip cameras

[camera1]
ip = "192.168.1.16"
username = "Smartcap1"
password = "ProjectSCN2021"

[camera2]
ip = "192.168.1.19"
username = "Smartcap2"
password = "ProjectSCN2021"




