# Config file for the ip cameras

[camera1]
ip = "192.168.1.42"
username = "Smartcap1"
password = "ProjectSCN2021"

[camera2]
ip = "192.168.1.43"
username = "Smartcap2"
password = "ProjectSCN2021"




